### ISSUE TITLE
Add ability to edit a site

### ISSUE THREAD

**Issue by jcaraballo17** [ODM2/ODM2WebSDL#34] opened 2017-02-13 21:56 UTC
Allow users to edit site information and add/edit/remove sensors.

**Comment by horsburgh** [comment] 2017-02-21 20:19
This is a duplicate of #4. Close both when complete.

**Comment by horsburgh** [comment] 2017-02-21 20:19
Nevermind - closing #4 now, it's not needed.

**Comment by SRGDamia1** [comment] 2017-05-31 16:21
This is complete, right?

**Closed** 2017-06-01 16:38 UTC
