### ISSUE TITLE
Delete unnecessary testing sites

### ISSUE THREAD

**Issue by fryarludwig** [ODM2/ODM2WebSDL#118] opened 2018-01-02 23:14 UTC
We have a number of unused testing sites that we should delete. If you're unsure about whether a site is actively used for testing, post about it here.

**Comment by fryarludwig** [comment] 2018-01-03 00:00
Super users can't currently delete sites they don't own until #117 makes it to production. As a workaround, super users can assign the site "deployed by" to themselves and then delete unused testing sites.

**Comment by horsburgh** [comment] 2018-01-12 20:11
This issue will be technically resolved when #117 gets pushed to production in this milestone. Given that there is a work around for this now (see comment from @fryarludwig above), people could be cleaning up now even without #117 going to production.

@fryarludwig, @jcaraballo17, @Maurier - can you guys all delete any testing sites that you have created, but no longer need.

@aufdenkampe and @SRGDamia1 - if you would do the same it would be great. 

Please keep useful example/testing sites if you need them, but note that you should be able to do most testing on the sandbox or on the staging server.

**Comment by aufdenkampe** [comment] 2018-01-23 17:57
I've deleted all of our dummy sites.

Let's make sure this works everywhere, for everyone, as part of this Bug Fix effort, before closing this issue.

**Comment by SRGDamia1** [comment] 2018-01-23 18:23
I've deleted all of the dummy sites I'd created for myself.  There are still several other sites out there that are tied to loggers that I programmed and gave out but were not actually ever installed.  (So they look like junk because they have fuzzy names and no data.)  I don't want to delete those because I did hand them off to other people and someday they may actually install their stations.

**Comment by fryarludwig** [comment] 2018-01-23 18:25
At this point I've also deleted all testing sites I'm not using.

**Comment by horsburgh** [comment] 2018-01-24 20:46
@SRGDamia1 and @aufdenkampe  - I just deleted one of my testing sites and so I've verified that the ability to delete sites is working. I'm assuming if there are any testing sites of yours that you still want to remove you can go ahead and do it at any point. Since there's not a bug in functionality here, I'm closing this issue.

**Closed by horsburgh** 2018-01-24 20:46 UTC

**Comment by aufdenkampe** [comment] 2018-01-26 20:43
@horsburgh, thanks for a final test! I think we are good to go!
